SOURCES = init.c kmain.c
TARGET = kernel.lib
# TARGETLIBS = \
# 	$(OBJECT_ROOT)/mm/mm.lib \
# 	$(OBJECT_ROOT)/drivers/vga/vga.lib \
# 	$(OBJECT_ROOT)/drivers/kbd/kbd.lib \

include $(BUILD)/Common.mk
