DIRS = drivers kernel mm

TARGET = program
TARGETLIBS = \
	$(OBJECT_ROOT)/kernel/kernel.lib \
	$(OBJECT_ROOT)/mm/mm.lib \
	$(OBJECT_ROOT)/drivers/vga/vga.lib \
	$(OBJECT_ROOT)/drivers/kbd/kbd.lib \

include $(BUILD)/Common.mk
